spring:
  redis:
    host: 192.168.1.225
    port: 39902
    password: W83BY*6V1LwaptvhzTN!K3MMDU
    database: 21


# SSE配置
sse:
  timeout: 60000
  heartbeatInterval: 30000

logging:
  level:
    com.block.sse.starter: DEBUG
    com.example.sse: DEBUG
